version: "3"
services:
  krakend_ce:
    #Watch mode is only to use on development
    image: devopsfaith/krakend:watch
    container_name: krakend_ce
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - rabbitmq
      - database
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    networks:
      - "microservices_network"

  # Swagger-ui
  swagger_ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger_ui
    ports:
      - "8081:8080"
    volumes:
      - ./config/swagger:/usr/share/nginx/html/swagger
    environment:
      - API_URL=/swagger/swagger.yml
    networks:
      - "microservices_network"

  # Statement-consult-api
  statement_consult_api:
    build:
      context: .
      dockerfile: ./microservices/statement-consult/Dockerfile
    container_name: statement_consult_api
    user: "1000:1000"
    volumes:
      - ./microservices/statement-consult:/app/statement-consult
    entrypoint: wait-for database:5432 -t 40 -- ./docker-entrypoint.sh
    working_dir: /app/statement-consult
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      PORT: 3000
      DB_NAME: statement_consult
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
    networks:
      - "microservices_network"

  # Statement-processor-api
  statement_processor_api:
    build:
      context: .
      dockerfile: ./microservices/statement-processor/Dockerfile
    container_name: statement_processor_api
    user: "1000:1000"
    volumes:
      - ./microservices/statement-processor:/app/statement-processor
    entrypoint: wait-for database:5432 -t 40 -- ./docker-entrypoint.sh
    working_dir: /app/statement-processor
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      PORT: 3004
      DB_NAME: statement_processor
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
    networks:
      microservices_network:
        aliases:
          - statement_processor_api

  # Depost-api
  deposit_api:
    build:
      context: .
      dockerfile: ./microservices/deposit/Dockerfile
    container_name: deposit_api
    user: "1000:1000"
    volumes:
      - ./microservices/deposit:/app/deposit
    entrypoint: wait-for database:5432 -t 40 -- ./docker-entrypoint.sh
    working_dir: /app/deposit
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      PORT: 3002
      DB_NAME: deposit
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
    networks:
      microservices_network:
        aliases:
          - deposit_api

  # Withdraw-api
  withdraw_api:
    build:
      context: .
      dockerfile: ./microservices/withdraw/Dockerfile
    container_name: withdraw_api
    user: "1000:1000"
    volumes:
      - ./microservices/withdraw:/app/withdraw
    entrypoint: wait-for database:5432 -t 40 -- ./docker-entrypoint.sh
    working_dir: /app/withdraw
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      PORT: 3003
      DB_NAME: withdraw
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
    networks:
      microservices_network:
        aliases:
          - withdraw_api

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass "redis_password"
    environment:
      - REDIS_PASSWORD=redis_password
    networks:
      - microservices_network

    volumes:
      - cache:/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - microservices_network
    logging:
      driver: "none"

  # Postgres
  database:
    image: postgres:13-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    logging:
      driver: none
    volumes:
      - development_data:/var/lib/postgresql/data
      - ./config/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - "microservices_network"

networks:
  microservices_network:
    driver: bridge

volumes:
  development_data:
  cache:
